version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1 
      - run: 
          working_directory: matching-doula 
          command: composer install -n --prefer-dist
      - run: 
          working_directory: matching-doula
          command: npm ci
      - run: 
          working_directory: matching-doula
          command: npm run dev
      - run:
          name: php test
          working_directory: matching-doula
          command: vendor/bin/phpunit