version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1 
      - restore_cache:
          working_directory: matching-doula
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: 
          working_directory: matching-doula 
          command: composer install -n --prefer-dist
      - save_cache:
          working_directory: matching-doula 
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
          - vendor
      - run: 
          working_directory: matching-doula
          command: npm ci
      - run: 
          working_directory: matching-doula
          command: npm run dev
      - run:
          name: php test
          working_directory: matching-doula
          command: vendor/bin/phpunit