version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1 
      - restore_cache:
          key: composer-v1-{{ checksum "matching-doula/composer.lock" }}
      - run: 
          working_directory: matching-doula 
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "matching-doula/composer.lock" }}
          paths:
          - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "matching-doula/package-lock.json" }}
      - run:
          name: npm ci
          working_directory: matching-doula
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
      - save_cache:
          key: npm-v1-{{ checksum "matching-doula/package-lock.json" }}
          paths:
            - node_modules
      - run: 
          working_directory: matching-doula
          command: npm run dev
      - run:
          name: php test
          working_directory: matching-doula
          command: vendor/bin/phpunit